version: "2"

services:
  datastore:
    build: internal/storage/image
    environment:
      - DATASTORE_PROJECT_ID=project-test
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081
    ports:
      - "8081:8081"
    command: --no-store-on-disk --consistency=1.0
