apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: playground-scio
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: playground-scio
  targetCPUUtilizationPercentage: 90
