apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: playground-java
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: playground-java
  targetCPUUtilizationPercentage: 90
