# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.


#Action used to trigger a failed check re-run within a PR using a comment. Add this action to your workflow with an if condition 
#to check if the comment is present 
#If the check is failed this will trigger it again. If its not failed a new instance of workflow will run which will not show in the status box or checks tab in the PR and can be found in the actions tab https://github.com/apache/beam/actions

name: "Rerun Job Action"
description: Re-runs a job that is attached to the PR as Check Run
inputs:
  pull_request_url:
    description: "The URL of the PR"
    required: true
  github_repository:
    description: "The GitHub repository"
    required: true
  github_token:
    description: "The GitHub token"
    required: true
  github_job:
    description: "The GitHub job"
    required: true
  github_current_run_id:
    description: "The GitHub current run id. Not the same that is fetched in this action"
    required: true


runs:
  using: composite
  steps:
  - name: Update check status
    uses: pyTooling/Actions/with-post-step@v0.4.6
    with:
      main: echo "Will update status in post"
      post: |
        echo ${{ steps }}





# # get current run status
# URL="${{github.api_url}}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}"
# STATUS=$(curl  \
# -H 'Authorization: Bearer ${{inputs.github_token}}' \
# -H "Accept: application/vnd.github+json" \
# -H "X-GitHub-Api-Version: 2022-11-28" \
# -s $URL | jq)
# echo $STATUS
# URL="${{github.api_url}}/repos/${{ github.repository }}/check-runs/${{env.new_check_id}}"
# curl -X PATCH \
# -H 'Authorization: Bearer ${{inputs.github_token}}' \
# -H "Accept: application/vnd.github+json" \
# -H "X-GitHub-Api-Version: 2022-11-28" \
# -s $URL \
# -d '{"details_url": "${{ github.server_url }}/actions/runs/${{ github.run_id }}","status": "completed", "conclusion": "'$STATUS'"}'