# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

steps:
  - name: ubuntu
    args:
      - '-c'
      - >-
        apt update > /dev/null

        apt-get install -y wget unzip software-properties-common git curl
        apt-transport-https ca-certificates gnupg jq > /dev/null

        echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | tee -a
        /etc/apt/sources.list.d/google-cloud-sdk.list

        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor > /etc/apt/trusted.gpg.d/google-cloud-sdk.gpg
        
        echo "deb [signed-by=/etc/apt/trusted.gpg.d/google-cloud-sdk.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | 
        tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        
        
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu 
        $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        
        apt install -y docker-ce > /dev/null

        wget
        https://releases.hashicorp.com/terraform/1.4.2/terraform_1.4.2_linux_amd64.zip 

        unzip terraform_1.4.2_linux_amd64.zip

        mv terraform /usr/local/bin/terraform

        apt update -y > /dev/null && apt install -y google-cloud-sdk
        openjdk-11-jdk kubectl > /dev/null 

        curl -fsSLo get_helm.sh
        https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 >
        /dev/null

        chmod +x get_helm.sh && ./get_helm.sh > /dev/null

        apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
        
        git clone --branch merged_pg_gke_deployment
        https://github.com/akvelon/beam.git

        cd beam

        mkdir playground/terraform/environment/$_ENVIRONMENT_NAME

        printf '%s\n' 'project_id = "$PROJECT_ID"' 'network_name =
        "$_NETWORK_NAME"' 'subnetwork_name = "$_SUBNETWORK_NAME"' 'gke_name =
        "$_GKE_NAME"' 'region = "$_PLAYGROUND_REGION"' 'zone =
        "$_PLAYGROUND_ZONE"' 'state_bucket = "$_STATE_BUCKET"' 'redis_name =
        "$_REDIS_NAME"' 'redis_tier = "$_REDIS_TIER"' 'min_count =
        "$_MIN_COUNT"' 'max_count = "$_MAX_COUNT"' 'app_engine_flag =
        "$_APPENGINE_FLAG"' 'ip-address-name = "$_IPADDRESS_NAME"'
        'repository_id = "$_REPOSITORY_ID"' 'service_account_id =
        "$_SERVICEACCOUNT_ID"' 'gke_machine_type = "$_GKE_MACHINETYPE"' >
        playground/terraform/environment/$_ENVIRONMENT_NAME/terraform.tfvars

        printf 'bucket = "$_STATE_BUCKET"' >
        playground/terraform/environment/$_ENVIRONMENT_NAME/state.tfbackend

        cat playground/terraform/environment/$_ENVIRONMENT_NAME/terraform.tfvars

        cat playground/terraform/environment/$_ENVIRONMENT_NAME/state.tfbackend

        ./gradlew playground:terraform:InitInfrastructure
        -Pproject_environment=$_ENVIRONMENT_NAME
    entrypoint: bash
timeout: 7200s
options:
  logging: CLOUD_LOGGING_ONLY
