steps:
  - name: ubuntu
    args:
      - '-c'
      - >-
        apt update > /dev/null

        apt-get install -y wget unzip software-properties-common git curl
        apt-transport-https ca-certificates gnupg jq > /dev/null

        echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | tee -a
        /etc/apt/sources.list.d/google-cloud-sdk.list

        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add
        -

        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

        add-apt-repository "deb [arch=amd64]
        https://download.docker.com/linux/ubuntu focal stable" > /dev/null

        apt install -y docker-ce > /dev/null

        wget
        https://releases.hashicorp.com/terraform/1.4.2/terraform_1.4.2_linux_amd64.zip 

        unzip terraform_1.4.2_linux_amd64.zip

        mv terraform /usr/local/bin/terraform

        terraform --version

        apt update -y > /dev/null && apt install -y google-cloud-sdk
        openjdk-11-jdk > /dev/null 

        git clone --branch merged_pg_gke_deployment
        https://github.com/akvelon/beam.git

        curl -fsSLo get_helm.sh
        https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 >
        /dev/null

        chmod +x get_helm.sh && ./get_helm.sh > /dev/null

        apt-get install google-cloud-sdk-gke-gcloud-auth-plugin

        cd beam

        mkdir playground/terraform/environment/myenv

        gcloud compute scp --zone=us-central1-a
        instance-1:/home/ruslan_ikhsanov/beam/playground/terraform/environment/myenv/terraform.tfvars
        playground/terraform/environment/myenv/terraform.tfvars

        gcloud compute scp --zone=us-central1-a
        instance-1:/home/ruslan_ikhsanov/beam/playground/terraform/environment/myenv/state.tfbackend
        playground/terraform/environment/myenv/state.tfbackend

        cat playground/terraform/environment/myenv/terraform.tfvars

        cat playground/terraform/environment/myenv/state.tfbackend

        gcloud auth configure-docker us-east1-docker.pkg.dev

        gcloud container clusters get-credentials --region us-east1-b
        playground-gke --project cloudbuildtest-382210

        ./gradlew playground:terraform:gkebackend -Pproject_environment=myenv
        -Pdocker-tag=$_TAG_NAME -Pdns-name=$_DNS_NAME -Psdk-tag=$_SDK_TAG
        -Pdocker-repository-root=$_ARTIFACT_REGISTRY_NAME
        -Pdatastore-namespace=$_DATASTORE_NAMESPACE

        cat playground/infrastructure/helm-playground/values.yaml
    entrypoint: bash
timeout: 7200s
logsBucket: 'gs://$_PLAYGROUND_TFSTATE_BUCKET'
options:
  machineType: E2_HIGHCPU_32
  logging: GCS_ONLY
substitutions:
  _PLAYGROUND_TFSTATE_BUCKET: tfstate-pg-ruslan1
