# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - name: ubuntu
    args:
      - '-c'
      - >-
        apt-get update >/dev/null && apt-get install -y git build-essential
        unzip software-properties-common ca-certificates curl wget gnupg
        lsb-release openjdk-11-jdk >/dev/null

        curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

        add-apt-repository "deb [arch=amd64]
        https://download.docker.com/linux/ubuntu focal stable" > /dev/null 

        apt update >/dev/null && apt install -y docker-ce >/dev/null

        curl -fsSLo get_helm.sh
        https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 >
        /dev/null 

        chmod +x get_helm.sh && ./get_helm.sh > /dev/null

        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee
        /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null 

        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg]
        https://apt.releases.hashicorp.com $(lsb_release -cs) main"  | tee
        /etc/apt/sources.list.d/hashicorp.list 

        apt update >/dev/null 

        apt install -y terraform > /dev/null

        curl -LO
        "https://storage.googleapis.com/kubernetes-release/release/$(curl -s
        https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"


        chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl

        git clone https://github.com/apache/beam.git

        cd beam

        mkdir playground/terraform/environment/$_ENVIRONMENT_NAME

        cat <<EOT >
        playground/terraform/environment/$_ENVIRONMENT_NAME/terraform.tfvars

        project_id = $PROJECT_ID

        network_name = $_NETWORK_NAME

        subnetwork_name=$_SUBNETWORK_NAME

        gke_name = $_GKE_NAME

        region = $_PLAYGROUND_REGION

        location = $_PLAYGROUND_ZONE

        state_bucket = $_STATE_BUCKET

        redis_name = $_REDIS_NAME

        min_count = $_MIN_COUNT

        max_count = $_MAX_COUNT

        gke_machine_type = $_GKE_MACHINE_TYPE

        app_engine_flag = $_APP_ENGINE_FLAG

        ip_address_name = $_IP_ADDRESS_NAME

        repository_id = $_REPOSITORY_ID

        service_account_id = $_SERVICE_ACCOUNT_ID

        EOT

        cat <<EOT >
        playground/terraform/environment/$_ENVIRONMENT_NAME/state.tfbackend

        bucket = $_STATE_BUCKET 

        EOT

        ./gradlew playground:terraform:InitInfrastructure -Pproject_environment="$_ENVIRONMENT_NAME" -Pdns-name="$_DNS_NAME"
    entrypoint: bash
timeout: 7200s
logsBucket: 'gs://playground-cloudbuild-logs-private'
options:
  machineType: E2_HIGHCPU_32
  logging: GCS_ONLY

