apiVersion: v1
kind: Pod
metadata:
  name: rabbit
  labels:
    purpose: rabbit-envars
spec:
  containers:
    - name: rabbit
      env:
        - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
          value: "rabbitmq_stream advertised_host localhost"