apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-go
  labels:
    app: backend-go
    type: backend
spec:
  template:
    metadata:
     name: playground
     labels:
       app: backend-go
       type: backend
    spec:
     containers:
     - name: playground-backend-go
       image: "{{ .Values.image.registry}}/{{ .Values.image.go_image }}:{{ .Values.image.tag }}"
       imagePullPolicy: {{ .Values.image.pullPolicy }}
       ports:
        - containerPort: 8080
       env:
         - name: CACHE_TYPE
           value: "remote"
         - name: CACHE_ADDRESS
           value: {{ .Values.redis_ip }}
  replicas: {{ .Values.replicaCount  }}
  selector:
    matchLabels:
     app: backend-go
