apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-java
  labels:
    app: backend-java
    type: backend
spec:
  template:
    metadata:
     name: playground
     labels:
       app: backend-java
       type: backend
    spec:
     containers:
     - name: playground-backend-java
       image: "{{ .Values.registry}}:{{ .Values.image.tag }}"
       imagePullPolicy: {{ .Values.image.pullPolicy }}
       env:
         - name: CACHE_TYPE
           value: "remote"
         - name: CACHE_ADDRESS
           value: "10.98.129.164:6379"
  replicas: {{ .Values.replicaCount  }}
  selector:
    matchLabels:
     app: backend-java
