apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-java
  labels:
    app: backend-java
    type: backend
spec:
  template:
    metadata:
     name: playground
     labels: 
       app: backend-java
       type: backend
    spec:
     containers: 
     - name: playground-backend-java
       image: "{{ .Values.image.registry}}/{{ .Values.image.java_image }}:{{ .Values.image.tag }}"
       imagePullPolicy: {{ .Values.image.pullPolicy }}
  replicas: {{ .Values.replicaCount  }}
  selector:
    matchLabels:
     app: backend-java
