apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-router
    type: backend
  name: playground-router
  annotations:
    cloud.google.com/backend-config: '{"default": "bkend-health"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - name: https       
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379  
  selector:
    app: backend-router
  type: {{ .Values.service.type }}
