apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-python
  labels:
    app: backend-python
    type: backend
spec:
  template:
    metadata:
     name: playground
     labels: 
       app: backend-python
       type: backend
    spec:
     containers: 
     - name: playground-backend-python
       image: us-central1-docker.pkg.dev/apache-beam-testing/playground-repository/beam_playground-backend-python:beta-version-v4
  replicas: 1
  selector:
    matchLabels:
     app: backend-python