apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-go
    type: backend
  name: playground-go
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: backend-go
  type: LoadBalancer