apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-java
    type: backend
  name: playground-java
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: backend-java
  type: LoadBalancer