apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-router
    type: backend
  name: playground-router
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: backend-router
  type: LoadBalancer
