name: kuber-bkend
on:
  push:
  
env:
  BEAM_ROOT_DIR: ../../
  BEAM_EXAMPLE_CATEGORIES: ../categories.yaml
  BEAM_VERSION: 2.40.0
  K8S_NAMESPACE: playground-backend
  HELM_APP_NAME: playground-backend
  DOCKERTAG: beta
jobs:
  deployBackend:
    name: init
    runs-on: ubuntu-latest
    steps:

      - name: Backend setup
        run: helm uninstall backend playground/infrastructure/helm-backend
