replicaCount: 1
image:
   java_image: beam_playground-backend-java
   go_image: beam_playground-backend-go
   router_image: beam_playground-backend-router
   scio_image: beam_playground-backend-scio
   python_image: beam_playground-backend-python
   pullPolicy: Always
   tag: "beta"

service:
   type: NodePort
   targetPort: 8080
   port: 443

autoscaling:
   enabled: false
   minReplicas: 1
   maxReplicas: 4
   targetCPUUtilizationPercentage: 80
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
