replicaCount: 1
project: s3d-pg
image:
   java_image: beam_playground-backend-java
   go_image: beam_playground-backend-go
   router_image: beam_playground-backend-router
   scio_image: beam_playground-backend-scio
   python_image: beam_playground-backend-python
   pullPolicy: Always
   registry: us-central1-docker.pkg.dev/s3d-pg/playground-repository
   tag: "beta"

service:
   type: NodePort
   targetPort: 8080
   port: 443

autoscaling:
   enabled: false
   minReplicas: 1
   maxReplicas: 4
   targetCPUUtilizationPercentage: 80
