replicaCount: 1
image:
   java_image: beam_playground-backend-java
   go_image: beam_playground-backend-go
   router_image: beam_playground-backend-router
   scio_image: beam_playground-backend-scio
   python_image: beam_playground-backend-python
   pullPolicy: Always
   tag: "testing"

service:
   type: NodePort
   targetPort: 8080
   port: 443

autoscaling:
   enabled: false
   minReplicas: 1
   maxReplicas: 4
   targetCPUUtilizationPercentage: 80

redis_ip: 10.87.130.148:6379
project_id: tour-of-beam-2
registry: us-central1-docker.pkg.dev/tour-of-beam-2/playground-repository
static_ip: 34.160.22.119
static_ip_name: tour-of-beam2-static
